version: '3.7'

services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra-net
    ports:
      - "9042:9042"

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra-net
    depends_on:
      - cassandra1

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra-net
    depends_on:
      - cassandra1
      - cassandra2

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-app
    volumes:
      - ./scripts:/app:rw
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    environment:
      CASSANDRA_HOSTS: "cassandra1,cassandra2,cassandra3"
      CASSANDRA_PORT: "9042"
      CASSANDRA_KEYSPACE: "my_keyspace"
    networks:
      - cassandra-net
    working_dir: /app
    ports:
      - "5000:5000"  # Если нужно открыть порт для веб-приложения

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:

networks:
  cassandra-net:
    driver: bridge